/*
This file is automatically generated
Lamp
C Source
*/

#include "Lamp.h"

#include "Ft_Gpu.h"
#include "Lamp_progmem.h"

Ft_Esd_BitmapInfo Lamp__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 144,
	.Height = 84,
	.Format = ARGB4,
	.Stride = 288,
	.Size = 24192,
	.ProgMem = Lamp_bin,
	.StorageSize = ((8851 + 3) >> 2),
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Type = ESD_RESOURCE_PROGMEM,
};

Ft_Esd_BitmapCell Lamp(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &Lamp__Info, 
		.Cell = cell 
	};
}


/* end of file */
